# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7b839e6ee10747cf6258fe2186f7a9e9ce23a559785255541ddefe82b8cfa369714d3a5b409ec4c02e8703649a8ef12a3465024a00945550a7c54557854161f

test:
  secret_key_base: 4419f9bfc339c1b1a331cc3c196d47f6584e8460df2af0636c75cb37934b7f052b152a1815ec3f11d095c5835b76362057d9474a6451ab8fda3598bf8cb8f078

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
